- name: copy default_site.html to ubuntu servers
  copy:
    src: default_site.html
    dest: /var/www/html/
    owner:   root
    group:   root
    mode:    0644
  when: ansible_distribution == "Ubuntu" 


- name: add suoder file for dawit user
  copy:
    src: suoder_dawit 
    dest: /etc/sudoers.d/ 
    owner: root
    group: root
    mode: 0440 