- name: Install httpd
  yum:
    name: 
          - apache2
          - htop 
    state: present
  when: ansible_distribution == "RedHat" 

- name: Install apache2
  apt:
    name: 
          - apache2
          - htop 
    state: present
  when: ansible_distribution == "RedHat" 

